[project]
name = "linux-cli-assistant"
version = "0.1.0"
requires-python = "==3.12.*"
dependencies = [
    "openai==2.37.0",
    "chromadb==1.5.9",
    "langchain-core==1.4.0",
    "langchain-text-splitters==1.1.2",
    "langchain-community==0.4.1",
    "langchain-google-genai==4.2.2",
    "pypdf==4.2.0",
    "python-dotenv==1.0.1",
    "streamlit==1.35.0",
    "pydantic==2.9.2",
    "ragas==0.1.22",
    "datasets==2.20.0"
]
